version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./backend:/app
      - /app/node_modules